language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    # - "pip install coverage"
    # - "pip install coveralls"
script:
    python setup.py test
    # - "coverage run --source=msobox setup.py test"
after_success:
    true
    # coveralls
# blacklist
branches:
  except:
    - development

# whitelist
branches:
  only:
    - master
